name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Good work, you've made your first issue! Our lovely contributors will take a look as soon as possible!"
        pr-message: "Hey! Good work, you've made your first pull request! One of our lovely members will take a look as soon as possible!"
